### ISSUE TITLE
x64dbg.portable outdated and old snapshot removed from upstream

### ISSUE THREAD

**Issue by obilodeau** [echizenryoma/Chocolatey-Package#8]
```
    virtualbox-iso: Software installed to 'C:\ProgramData\chocolatey\lib\ghidra'
    virtualbox-iso: Progress: Downloading x64dbg.portable 20190817.1748... 100%
    virtualbox-iso:
    virtualbox-iso: x64dbg.portable v20190817.1748 [Approved]
    virtualbox-iso: x64dbg.portable package files install completed. Performing other installation steps.
    virtualbox-iso: Attempt to get headers for https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-17_17-48.zip failed.
    virtualbox-iso: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-17_17-48.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
    virtualbox-iso: Downloading x64dbg
    virtualbox-iso: from 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-17_17-48.zip'
    virtualbox-iso: ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-17_17-48.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
    virtualbox-iso: This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
    virtualbox-iso: The install of x64dbg.portable was NOT successful.
```

I'm also going to file an issue upstream asking them to keep their old snapshot up a little longer.
